apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-prom-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: demo-prom-app
  endpoints:
  - port: web