apiVersion: v1
kind: Pod
metadata:
  name: demo-liquibase
spec:
  containers:
  - image: "{{ .Values.demo.image }}:{{ .Values.demo.tag }}"
    imagePullPolicy: IfNotPresent
    name: demo-liquibase
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
      - mountPath: "/var/secrets"
        name: database-credentials
  volumes:
  - name: database-credentials
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "{{ .Values.secretProviderClass.name }}"
  serviceAccountName: "{{ .Values.serviceAccount.name }}"

