apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.serviceAccount.name }}"
  annotations:
    iam.gke.io/gcp-service-account: "gke-workload@{{ .Values.project }}.iam.gserviceaccount.com"
