apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings
  labels:
    account: ratings
---
apiVersion: v1
kind: Pod
metadata:
  name: ratings
  labels:
    app: ratings
    version: v1
spec:
  serviceAccountName: whatsmyname
  containers:
  - name: ratings
    image: docker.io/istio/examples-bookinfo-ratings-v1:1.17.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 9080
    securityContext:
      runAsUser: 1000
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
