apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: list-pods
 namespace: sa-demo
rules:
 - 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: list-pods_demo-sa
 namespace: sa-demo
roleRef:
 kind: Role
 name: list-pods
 apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: ServiceAccount
   name: whatsmynameagain
   namespace: sa-demo
