apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: list-pods
 namespace: wsc-kubernetes-training-sa
rules:
 - apiGroups: [""] # "" indicates the core API group
   resources: ["pods"]
   verbs: ["list"]