apiVersion: v1
kind: Pod
metadata:
  name: wsc-db-client
  namespace: wsc-training-db
spec:
  serviceAccountName: wsc-db-client
  containers:
  - image: docker.io/codingpuss/postgres-client
    imagePullPolicy: IfNotPresent
    name: mypod
    resources:
      requests:
        cpu: 100m
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
      - mountPath: "/var/secrets"
        name: database-credentials
  volumes:
  - name: database-credentials
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: training-database-credentials

