apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: training-database-credentials
  namespace: wsc-training-db
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/wsc-cnd-dev-k8s-X/secrets/training-database-credentials/versions/latest"
        path: "value"