apiVersion: v1
kind: Namespace
metadata:
  name:  wsc-training-db
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: training-database-credentials
  namespace: wsc-training-db
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/wsc-cnd-dev-k8s-0/secrets/training-database-credentials/versions/latest"
        path: "value"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wsc-db-client
  namespace: wsc-training-db
  annotations:
    iam.gke.io/gcp-service-account: gke-workload@wsc-cnd-dev-k8s-0.iam.gserviceaccount.com
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-liquibase
  namespace: wsc-training-db
spec:
  initContainers:
  - name: db-migration
    image: docker.io/rdavaze/liquibase-postgres:4.15.0
    imagePullPolicy: IfNotPresent
    env:
      - name: CREDENTIALS_FILE
        value: /var/secrets/value
    volumeMounts:
      - mountPath: "/var/secrets"
        name: database-credentials
        readOnly: true
  containers:
  - image: docker.io/codingpuss/postgres-client
    imagePullPolicy: IfNotPresent
    name: mypod
    resources:
      requests:
        cpu: 100m
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
      - mountPath: "/var/secrets"
        name: database-credentials
  volumes:
  - name: database-credentials
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: training-database-credentials
  serviceAccountName: wsc-db-client

