apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
    service: details
spec:
  type: NodePort
  selector:
    app: details
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
