apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: image
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml
