apiVersion: v1
kind: Pod
metadata:
  name: bookinfo
spec:
  containers:
    - name: productpage
      image: docker.io/istio/examples-bookinfo-productpage-v1:1.17.0
      imagePullPolicy: IfNotPresent

